#!/bin/sh

bar=(
  color=0xff000000
  # color=0xff2e2f3a        # catpucin
  height=35
  sticky=on
  padding_left=7
  padding_right=7
)

default=(
  icon.drawing=off
  label.padding_left=4
  label.padding_right=4
  label.color=0xffcad3f5
)

sketchybar \
  --bar "${bar[@]}" \
  --default "${default[@]}"

# sketchybar \
#   --add item space left \
#   --set space script='sketchybar --set $NAME label="[$(echo "$INFO" | jq .[])]"'\
#   --subscribe space space_change


# sketchybar \
#   --add item app_name left \
#   --set app_name script='sketchybar --set $NAME label="$USER::$INFO"' \
#   --subscribe app_name front_app_switched

# sketchybar \
#   --add item nepdate right \
#   --set nepdate script='sketchybar --set $NAME label="$(nepcal date)"' \
#              update_freq=300 \
#   --subscribe nepdate system_woke

# sketchybar \
#   --add item time right \
#   --set time script='sketchybar --set $NAME label="$(date "+%H:%M")"' \
#              update_freq=30 \
#   --subscribe time system_woke



# sketchybar \
#   --add item ip right \
#   --set ip script='sketchybar --set $NAME label="/$(ipconfig getifaddr en0)/"'\
#   --subscribe ip wifi_change

sketchybar --update
